version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      POSTGRES_USER: burlamask
      POSTGRES_PASSWORD: 37uFz7O3
      GOOGLE_APPLICATION_CREDENTIALS: /../../burlamask-ada-6e214da98fe3.json
      GOOGLE_FOLDER_ID: 1j-QnGuiz4qQNV0Gbsulx_H6QfAYfDG82
      NODE_OPTIONS: --max_old_space_size=4096
    ports:
      - "3000:5000"
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: burlamask
      POSTGRES_PASSWORD: 37uFz7O3
      POSTGRES_DB: burlamask
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 37uFz7O3
    ports:
      - "5050:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8000:3000"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python:/app/data/
    ports:
      - "4000:4000"

volumes:
  pgdata:
